export const ApprovalLevelConstants = {
    PROFESSIONAL_DEVELOPMENT_APPROVAL_ID: 174,
    PROFESSIONAL_DEVELOPMENT_REVIEWER_PROCESS_ID: 125,
    PROFESSIONAL_DEVELOPMENT_APPROVER_PROCESS_ID: 126,
    PROFESSIONAL_DEVELOPMENT_USER_PROCESS_ID: 124,

    PROFESSIONAL_DEVELOPMENT_USER_EXAM_SESSION_PROCESS_ID: 130,
    PROFESSIONAL_DEVELOPMENT_REVIEWER_EXAM_SESSION_PROCESS_ID: 129,
    PROFESSIONAL_DEVELOPMENT_APPROVER_EXAM_SESSION_PROCESS_ID: 131,
    EXAM_TYPE_REVIEW_APPR_INDEX: 1,
    EXAM_TYPE_ENTRY_APPR_INDEX: 1,
}
