export const UserConstants = {
  FIMM_PDS_USER: { GROUP_NAME: 'OFFICER', DEPARTMENT: 'PROFESSIONAL DEVELOPMENT', DIVSION: 'INDUSTRY SERVICES DIVISION' },
  FIMM_PDS_REVIEWER: { GROUP_NAME: 'HOD', DEPARTMENT: 'PROFESSIONAL DEVELOPMENT', DIVSION: 'INDUSTRY SERVICES DIVISION' },
  FIMM_PDS_APPROVER: { GROUP_NAME: 'GM', DEPARTMENT: 'PROFESSIONAL DEVELOPMENT', DIVSION: 'INDUSTRY SERVICES DIVISION' },
}
